### ISSUE TITLE
E-platform styling issues

### ISSUE THREAD

**Issue by andlbrei** [dnbexperience/eufemia#4524]
## 🐛 Bug Report

(Not really a bug)

In `src/style/core/reset.scss` certain styling is set, seemingly to help with e-platform styling.  
Several users (including me) who are developing new apps have needed to override some of these to get their apps to look correct on e-platform.  

Now, I don't know why this was introduced, I am sure it was needed at the time, but it might be time to consider removing/deprecating some of this CSS. Or finding some other solution so that not every new e-platform app needs to override e-platform specific Eufemia styles.

Eufemia CSS:
```css
// reset ePlatform css
@mixin resetLegacyStyles() {
...
    body#dnbLayoutDefault #wrapper,
    body#dnbLayoutDefaultStartPage #wrapper {
      width: 100%;
      max-width: 60rem;
    }

    ul {
      list-style: initial;
    }
}
```

Needed overrides:
```css
// E-platform styles
// NB: These styles fix some layout issues when deploying to e-platform
div#wrapper {
  max-width: none !important;
  padding: 0px;
}

ul.quickMenuList,
ul[role='presentation'],
ul.ui-corner-all {
  list-style-type: none !important;
}

// - End of e-platform styles

```

## Eufemia Version
10.63.0
